### ISSUE TITLE
Possible gas estimation flakiness in calling `approve`

### ISSUE THREAD

**Issue by hpihkala** [omni/omnibridge-ui#180]
- [Here's](https://etherscan.io/tx/0x2968b5c26795d9606e53eb5b3088e58ffb8768c8d97d94cbe93a96c9cb79f552) my first attempt at "Unlocking" (`approve`) `DATA` for usage with the OmniBridge. As you can see, it ran out of gas. The UI came up with a limit of 45,160 gas, which wasn't enough and the transaction failed. ❌ 

- [I tried again on the same account](https://etherscan.io/tx/0xce223690b2f9f70a9f0afb91210c02a29a78654c29360385dd92e9e1a56e51de), this time manually editing the gas limit in Metamask and forcing it to 100,000 to see how much the `approve` actually needs. The transaction succeeded and used 45,184 gas - so the first tx only fell short by 24 gas!

- [I tried on another account](https://etherscan.io/tx/0x5dc9b84ec8a7887dd0b8756901b9aeea1cb9b316227eb4d6575d025299ee8c37) which had already interacted with DATA before (but not with the bridge). This time it estimated 45,172 which was exactly right, success. ✅

- To remove all doubt, I pulled a fresh account that had never seen DATA nor the bridge before, sent some DATA to it, and [approved the bridge](https://etherscan.io/tx/0xef20459f72ff6d5cb282c3f097cb4aa22f385da71bd0e0e4c183f65b19f4dd8d). This time the UI estimated 45,160 (the same amount as on the transaction that failed!), but this time it was exactly right, success again. ✅

I understand you're just pulling the gas estimates via the library/wallet, and the app isn't opinionated on those. As I couldn't get it to fail again, **this issue is probably safe to ignore for now**, so feel free to close this. I thought I'd still report my experience as FYI in case you guys happen to encounter it further down the road. @dan13ram

**Comment by hpihkala** [comment]
Actually, encountered this again today in [this tx](https://etherscan.io/tx/0x45217256b5d83bbc559e8803950a7b1de9a4234bc2eb802ac2ae073eb47c3f3e). Same specs as before: the estimate was 45,160 gas, which wasn't enough and the tx failed. With current gas prices, that's $20 bucks wasted every time it happens to fail. I hope this only happens to me :)

Again, it was an account that hadn't approved the bridge before, but had probably approved some other contracts for the same token. The pattern is not clear, and it could also be that there's no pattern at all. I haven't tried bridging other tokens yet to see if the same issue might occur there.

**Comment by dan13ram** [comment]
Closing since this seems like a one-time thing that hasn't occurred since. Please reopen if you see it again.

Also `approve` failing for a particular token might mean the issue may be in the token contract.
