### ISSUE TITLE
BSC - xDAI subgraph is down

### ISSUE THREAD

**Issue by dan13ram** [omni/omnibridge-ui#230]
The subgraph at https://thegraph.com/explorer/subgraph/maxaleks/bsc-to-xdai-omnibridge?selected=logs has not been tracking executions data recently. 

The the following log is being emitted repeatedly: 
```
Trying again after eth_call RPC call failed (attempt #10) with result Err(Web3Error(Transport("Unexpected response status code: 503 Service Unavailable"))), block_hash: 0xdf4585ba808c2511290f60ef552c16df99f96024ee55ff088ddb10de49992b69, block_number: 7239927
```

This is a WARNING log, so the subgraph hasn't thrown any errors. But unfortunately this breaks our frontend. 
xDAI => BSC transfers albeit claimed still show `Claim` button on the UI.

There may be other issues yet to be surfaced.

**Comment by dan13ram** [comment]
Update: TheGraph team are aware of this issue (as per their discord).
The issue seems to be on Binance side, wherein the RPC node(s) used by TheGraph's hosted service is(are) returning 503s since the past few days. It has been reported to them and we are waiting on an update.

**Comment by akolotov** [comment]
@dan13ram thanks for updates.

Do you think it makes sense to extend the warning like this: "The Graph service may not work properly and some transfers may not display. You can use the form below to claim your tokens. If your transfer is still displayed as unclaimed double check its status in AMB Live Monitoring app by pressing a link in the Sending Tx column."
