### ISSUE TITLE
Events filtering bug

### ISSUE THREAD

**Issue by maxaleks** [omni/omnibridge-ui#236]
https://github.com/omni/omnibridge-ui/blob/master/packages/react-app/src/hooks/useManualClaim.js#L48 - the block number in this filtering is incorrect. We should use a different block number for each bridge or just use 0.

**Comment by akolotov** [comment]
Consider to have this configurable through an environment variable

**Comment by akolotov** [comment]
Moreover it is possible to check if enough confirmations collected without logs at all. Look at this code in the AMB contract:
https://github.com/poanetwork/tokenbridge-contracts/blob/004d466a3d593e6304e52c74e6c3e801b6a33b32/contracts/upgradeable_contracts/arbitrary_message/BasicHomeAMB.sol#L79

**Comment by dan13ram** [comment]
I've changed the logic to not use events anymore, please check :)
