### ISSUE TITLE
Deployment Documentation

### ISSUE THREAD

**Issue by q9f** [omni/omnibridge-ui#240]
Excuse my ignorance. How would you deploy the Omnibridge UI? Are there any docs available?

Any pointers would be appreciated. I planned to use the Tokenbridge UI but it was removed recently apparently.

https://github.com/poanetwork/tokenbridge/issues/547

**Comment by akolotov** [comment]
@q9f hi! In order to understand your need better there are few questions: 
  - are you planning to use the OmniBridge contracts?
  - are the chains the OmniBridge is going to be used with supported by the graph?
Thanks

**Comment by q9f** [comment]
Hi!

>     * are you planning to use the OmniBridge contracts?

Yes, we already deployed them!
 
>     * are the chains the OmniBridge is going to be used with supported by the graph?

No, what's required?

**Comment by akolotov** [comment]
@q9f sorry for delay

> No, what's required?

You need to ask the Graph team to deploy the graph service for your chain. Or try to deploy the graph service by your own. As soon as it is available we can assist you in configuring the graph queries for your instance of OB UI.
