### ISSUE TITLE
MKR won't load in omnibridge for xdai to eth transfer

### ISSUE THREAD

**Issue by Humpydumpy** [omni/omnibridge-ui#241]
I am unable to move MKR from xdai to eth at omnibridge. Getting this error when selecting MKR from token list: 
Error
Cannot fetch token details. Wait for a few minutes and reload the application

Googled this known issue:
 https://githubmemory.com/repo/xdaichain/omnibridge/issues/160
'The issue is due to the reason that MKR does not follow the ERC20 standard and uses the bytes32 type for the name field instead of the string type."

 Is this string type issue still unresolved?

**Comment by dan13ram** [comment]
@Humpydumpy Thank you for reporting this. Looks like the bug was not fully fixed. 
The linked PR once merged should fix the issue :)
