### ISSUE TITLE
Discover a transaction replacing the transaction initiated by OB UI

### ISSUE THREAD

**Issue by akolotov** [omni/omnibridge-ui#259]
MetaMask allows to replace a transaction by increasing the gas price so the transaction generated by OB UI will be never mined. Consider to improve the transaction tracking process as so it will discover if the transaction was replaced as so the status of the transaction in the modal window is displayed adequately - a new transaction is used to continue tracking.

**Comment by dan13ram** [comment]
I'll be using this to track transactions being replaced or cancelled
https://blog.ricmoo.com/highlights-ethers-js-may-2021-2826e858277d
