### ISSUE TITLE
Switch network automatically when a user tries to claim tokens

### ISSUE THREAD

**Issue by maxaleks** [omni/omnibridge-ui#260]
If the wrong network is selected, we can open the Metamask window to switch the network and then open another window to send the transaction

You can check how it works on https://bridge.xdaichain.com

**Comment by akolotov** [comment]
@maxaleks may you check if this is the same issue as https://github.com/omni/omnibridge-ui/issues/253? If so, may you confirm that the changes work as you are expecting?

**Comment by maxaleks** [comment]
@akolotov I checked and it doesn't work on the History page
