### ISSUE TITLE
Add POA ↔ xDai bridge to OmniBridge UI

### ISSUE THREAD

**Issue by ulyanas** [omni/omnibridge-ui#278]
- Add POA ↔ xDai bridge to OmniBridge bridge selection 
- POA ↔ xDai bridge should allow users to connect their Web3 wallets and swap assets between POA and xDai networks via Omni Bridge UI 
- Need to wrap POA into wPOA similar to wrapping BNB when bridging from BSC 
- "Receive POA" switch is also needed when bridging wPOA back to POA Network to receive unwrapped token

![image](https://user-images.githubusercontent.com/6618204/130788353-84aaab75-acd8-43b9-b4db-3c9e9f004b13.png)

**Comment by akolotov** [comment]
Eventually, we have deployed AMB and OB contracts for this bridge. Their addresses can be found in the corresponding part of the documentation: https://docs.tokenbridge.net/poa-xdai-amb/about-the-poa-xdai-amb.

Please also note, that it should be an ability to transfer POA native tokens in form of ERC20 WPOA to the xDai chain and vice versa similar to the functionality we have for the BSC-xDai Omini bridge (BNB<->WBNB). The corresponding section in the documentation was also created.

**Comment by ulyanas** [comment]
@dan13ram  Any updates on POA ↔ xDai bridge?

**Comment by dan13ram** [comment]
Not yet.
@sunguru98 is working on it, and he will have some updates in 2 days time :)
