### ISSUE TITLE
Modal window disappears if a user changes the chain by clicking the link

### ISSUE THREAD

**Issue by akolotov** [omni/omnibridge-ui#299]
In the scenario when a user tries to add a token to MM the following modal window appears.

![image](https://user-images.githubusercontent.com/20793260/140696660-fa1cb3a4-460c-4516-bfa0-7afabe8655a2.png)

if the user clicks the link following after the text "Please switch your wallet to ...", the MM window occurs but the modal one disappears and the user is not able to add the token.

At the same time if the chain is changed in MM directly, the modal window is still on the screen - nothing blocks to add the token.

**Comment by dan13ram** [comment]
@akolotov For me it works correctly. Can you check again ?
https://user-images.githubusercontent.com/10012209/140889986-a4f34997-4380-4e5f-9261-1e7cf1314822.mp4

**Comment by akolotov** [comment]
May it relate to POA-xDAI direction?

https://user-images.githubusercontent.com/20793260/140894462-4a221a28-a96e-40bb-a11a-6341c0b78795.mov

**Comment by akolotov** [comment]
@dan13ram please take a look at the video in the comment above

**Comment by dan13ram** [comment]
@akolotov Could you help me with version of metamask and browser that you're using? 
I'm using the latest Brave browser and it is working for me even with POA - xDAI direction.

Here is the screen capture:

https://user-images.githubusercontent.com/10012209/141060137-deeeb10d-13d5-41a9-84ba-ce7913543794.mov

**Comment by akolotov** [comment]
This was reproduced on the Google Chrome v95.0.4638.69 and MM v10.4.1. And we received reports from other users also.

**Comment by dan13ram** [comment]
Thanks @akolotov with your help I was able to reproduce it. 🙏🏽 

I've added the fix in #305
