### ISSUE TITLE
Warning messages for STAKE tokens

### ISSUE THREAD

**Issue by akolotov** [omni/omnibridge-ui#300]
Consider to add additional warnings for the following cases:
  - an attempt to bridge STAKE from xDAI to BSC, the message should be
  _Bridging STAKE token from the Binance Smart Chain to the Ethereum Mainnet DOES NOT unlock xDai-pegged STAKE token. If you want STAKE token on the Ethereum Mainnet <bridge it back to the xDai chain first (direct link for bridging STAKE to the xDai chain from BSC)>._
  - an attempt to bridge STAKE from BSC to Ethereum Mainnet, the message should be
  _Bridging STAKE token from the xDai chain the the Binance Smart Chain to the Ethereum Mainnet DOES NOT mint Binance-pegged STAKE token. Don't send minted token to the Binance deposit address!_

**Comment by dan13ram** [comment]
@akolotov Just to be clear 
The first message should be shown for from token address `0xb7D311E2Eb55F2f68a9440da38e7989210b9A05e` from xDai chain to BSC,
and the second message should be shown for `0x24e5CF4a0577563d4e7761D14D53C8D0b504E337` from BSC to Mainnet and not for `0xe55e614862694214f0339adb551393cb56149323` to Mainnet.

I've implemented as above in PR #301

**Comment by akolotov** [comment]
@dan13ram sorry it seems that I messed with the messages.

_Bridging STAKE token from the Binance Smart Chain to the Ethereum Mainnet DOES NOT unlock xDai-pegged STAKE token. If you want STAKE token on the Ethereum Mainnet <bridge it back to the xDai chain first (direct link for bridging STAKE to the xDai chain from BSC)>._ must be for the **ETH-BSC** bridge.

_Bridging STAKE token from the xDai chain to the Binance Smart Chain DOES NOT mint Binance-pegged STAKE token. Don't send minted token to the Binance deposit address!_ must be for the **BSC-xDAI** bridge.
