### ISSUE TITLE
Disable ability to transfer STAKE token

### ISSUE THREAD

**Issue by akolotov** [omni/omnibridge-ui#310]
If a user tries to choose a STAKE token to transfer through the bridge a modal window must appear informing that the transfer for STAKE tokens is disabled and the user needs to swap STAKE tokens to GNO. For more information the user must be directed to the following page: https://www.xdaichain.com/for-stakers/stake-gno-swap.

**Comment by dan13ram** [comment]
@akolotov Should we display this more as a warning and allow bridging, or do we disable bridging of STAKE tokens on omnibridge from any network ?

For example, I see a situation where someone has STAKE on Binance and wants to bridge it to Gnosis Chain or Mainnet before they can swap for GNO tokens.

**Comment by akolotov** [comment]
Let's disable bridging STAKE token at all. If it is needed users still are able to bridge STAKE by interacting with the contracts directly (e.g. in bscscan and blockscout).
