### ISSUE TITLE
Replace xDai labels by Gnosis Chain

### ISSUE THREAD

**Issue by akolotov** [omni/omnibridge-ui#311]
Please go through all the pages/labels which mention xDai or the xDai chain and replace them by GC or Gnosis Chain.

For example, `XDAI` here 

![image](https://user-images.githubusercontent.com/20793260/148050634-00b82f96-d346-4bde-b875-2b4b877c1a0d.png)

can be replaced by `GC`.

Whereas the xDai label on the history page.

![image](https://user-images.githubusercontent.com/20793260/148050767-6662b021-bbd5-4b72-8f6a-29f1dbaf76ad.png)

can be replaced by `Gnosis Chain`.

The filed on the Settings window

![image](https://user-images.githubusercontent.com/20793260/148050924-98bda4dc-04bd-4179-94c4-4d7c9e983658.png)

should be replaced by `Gnosis Chain`.

And this is only obvious examples. Please go through the error and warning messages to make the corresponding changes there as well.

**Comment by ulyanas** [comment]
+ https://numerous-basement-567.notion.site/OmniBridge-rebranding-for-Gnosis-Chain-93317ababa7a4556be223d93d7b8f554
