### ISSUE TITLE
Disable ability to transfer USDC and DAI from BSC

### ISSUE THREAD

**Issue by akolotov** [omni/omnibridge-ui#316]
If a user tries to choose Binance-Peg USDC or Binance-Peg DAI tokens to transfer through the bridge from BSC a modal with a text like the following window must appear:

- Bridging of Binance-Peg USDC tokens to the Gnosis Chain is disabled, please use [Xpollinate](https://xpollinate.io/) bridge instead.
- Bridging of Binance-Peg DAI tokens to the Gnosis Chain is disabled, please use [Xpollinate](https://xpollinate.io/) bridge instead.

Address of USDC on BSC: https://bscscan.com/token/0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d
Address of DAI on BSC: https://bscscan.com/token/0x1af3f329e8be154074d8769d1ffa4ee058b1dbc3

Since the Connext protocol now has enough liquidity for such transfers, these changes must simplify the UX.

Transfers for the corresponding bridged tokens https://blockscout.com/xdai/mainnet/token/0xD10Cc63531a514BBa7789682E487Add1f15A51E2 and https://blockscout.com/xdai/mainnet/token/0xFc8B2690F66B46fEC8B3ceeb95fF4Ac35a0054BC should be still allowed.

**Comment by dan13ram** [comment]
> Address of USDC on BSC: https://bscscan.com/token/0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d
Address of DAI on BSC: https://bscscan.com/token/0x1af3f329e8be154074d8769d1ffa4ee058b1dbc3

@akolotov Should the bridging of these two tokens be disabled on BSC => ETH as well ?
