### ISSUE TITLE
"Error: Please specify amount less than 0" appears

### ISSUE THREAD

**Issue by akolotov** [omni/omnibridge-ui#339]
One of our users reported that she got the following message "Error: Please specify amount less than 0". The message does not look very informative and logical since it is not possible to enter negative amount of token.

Could you as part of work on the issue please investigate 
1. Why could such kind of issue appear?
2. Which message could be reported instead to help users with the issue troubleshooting?

**Comment by julien51** [comment]
confirming I have seen this issue when trying to transfer some UDT : 0x90DE74265a416e1393A450752175AED98fe11517
<img width="1393" alt="Screen Shot 2022-04-27 at 7 49 31 AM" src="https://user-images.githubusercontent.com/17735/165511933-6add366d-d675-4922-b8bc-57701bd3dfce.png">

**Comment by julien51** [comment]
I have previously approved (Unlocked) the right ERC20 amount.

**Comment by claberus** [comment]
This problem persists. I found that deleting the commas separator fixes the issue.
@akolotov
