### ISSUE TITLE
Inconsistent view for decimals

### ISSUE THREAD

**Issue by ulyanas** [omni/omnibridge-ui#343]
<img width="1175" alt="Screenshot at Apr 27 11-35-29" src="https://user-images.githubusercontent.com/6618204/165478050-950757af-49ba-4795-adc4-5e6356f743e5.png">

**Comment by akolotov** [comment]
Probably it is related to the Region settings. Mine is Russia and I also has the same behaviuor.

**Comment by dan13ram** [comment]
> Probably it is related to the Region settings. Mine is Russia and I also has the same behaviuor.

Thank you! I was able to reproduce it that way

**Comment by ulyanas** [comment]
Yes, it depends on the locale. Here is mine:
<img width="585" alt="image" src="https://user-images.githubusercontent.com/6618204/165841691-8dda6450-111f-4edd-a20d-2860ac21a99c.png">

**Comment by akolotov** [comment]
Even after the merge of #346, the issue still exists: https://github.com/omni/omnibridge-ui/pull/346#issuecomment-1114800903
