### ISSUE TITLE
Can we reinstate Bridging of Binance-Peg USDC tokens to the Gnosis Chain (currently disabled)

### ISSUE THREAD

**Issue by JourneyJilly** [omni/omnibridge-ui#348]
![bild](https://user-images.githubusercontent.com/74075045/166120933-9bee5bc4-9436-4a1e-8cfe-bb96de5c879b.png)
There is decent liquidity here here but bridging is disabled.

Is there a reason for this that I missed? I would like to be able to move over more 0xd10cc63531a514bba7789682e487add1f15a51e2 to Gnosis.

I would like this token to continue to be supported

**Comment by akolotov** [comment]
No, so far we don't plan to support to transfer of Binance-Peg USDC to the Gnosis Chain.
