### ISSUE TITLE
"Internal JSON-RPC error" when amount exceeds the daily limit

### ISSUE THREAD

**Issue by akolotov** [omni/omnibridge-ui#360]
If a user tries to transfer amount that exceeds the daily limit the app displays "Internal JSON-RPC error" instead of a proper message.

![image](https://user-images.githubusercontent.com/20793260/168166632-8780e93f-674a-48dd-82b3-2f7e792f2fd1.png)

**Comment by dan13ram** [comment]
@akolotov Is this still relevant now that we've added the check and the sentry log ?

**Comment by akolotov** [comment]
Addressed by #346
