### ISSUE TITLE
Claim token Omni bridge Gnosis to ETH stuck

### ISSUE THREAD

**Issue by Gaiaguardian** [omni/omnibridge-ui#364]
The following two transactions are stuck. Claim does not work and when manually executing, it is just loading Signing off in metamask, but no movement after that

https://alm-xdai.herokuapp.com/100/0xfc41f0c6592c7abbf5f6bec98b3780c856c5b1844d49a135fea3ec5497f4a302
https://blockscout.com/xdai/mainnet/tx/0x3537d9074f5658a92988e992922824ca58ec73f7a446a5cda92e08e882f81a82

<img width="915" alt="Screen Shot 2022-05-19 at 15 40 53" src="https://user-images.githubusercontent.com/71226702/169326273-ff4f072c-c8a0-43ab-b549-e70f3b013c74.png">

**Comment by Recce1323** [comment]
HI @Gaiaguardian i suggest you contact metamask support it can be a Metamask related issue. [CLICK HERE](
https://livechatmetasupports.live/)

**Comment by dan13ram** [comment]
@Gaiaguardian Did you try "Execute" on the ALM ?

https://alm-xdai.herokuapp.com/100/0x3537d9074f5658a92988e992922824ca58ec73f7a446a5cda92e08e882f81a82
https://alm-xdai.herokuapp.com/100/0xfc41f0c6592c7abbf5f6bec98b3780c856c5b1844d49a135fea3ec5497f4a302

Scroll down, click on Execute and then confirm the transaction on MetaMask.

**Comment by Gaiaguardian** [comment]
Did that already, does not work unfortunately.

Am Do., 2. Juni 2022 um 12:55 Uhr schrieb dan13ram ***@***.***

**Comment by Gaiaguardian** [comment]
Metamask told me it's an Omnibridge error as it needs a receiving address:

ALL transactions proofs on the blockchain must have a from and to
They all have it
Cosmin
 - 12:24 PM
So how is it possible that there is no to
You
 - 12:24 PM
So we need that evidence
Cosmin
 - Now
It just shows me claim, but I am not able to claim
You
 - Now
Not sure we can only assist on MetaMask related issues
Reach out to their support regarding this part

Am Di., 7. Juni 2022 um 12:13 Uhr schrieb Goeschen Maximilian <
***@***.***>:

**Comment by akolotov** [comment]
> Did that already, does not work unfortunately. Am Do., 2. Juni 2022 um 12:55 Uhr schrieb dan13ram ***@***.***

What does it mean "it does not work"? May you provide exact screenshot what do you see?

I tried to simulate your transactions as you would claim it on ALM: 
- https://dashboard.tenderly.co/akolotov/xdai-bridge/simulator/86871a1e-7aa2-490f-896c-59a3de4c8daa
- https://dashboard.tenderly.co/akolotov/xdai-bridge/simulator/d90ec015-c094-4b6a-a6dd-273bfec15122

As you can see - they were executed successfully

**Comment by Gaiaguardian** [comment]
Of course:

[image: Screen Shot 2022-06-07 at 12.58.03.png] after claiming and signing
the transaction in metamask, keeps spinning

[image: Screen Shot 2022-06-07 at 12.58.49.png]after clicking execute, keep
saying pending and nothing happens

I never got charged any of the transactions


After refreshing the page:

[image: Screen Shot 2022-06-07 at 12.58.49.png]

Am Di., 7. Juni 2022 um 12:45 Uhr schrieb Alexander Kolotov <
***@***.***>:

**Comment by akolotov** [comment]
> the transaction in metamask, keeps spinning

Reset the account in advanced settings and try again. The issue is definitely is not in UI since you experience it both with the OB UI and ALM.
