### ISSUE TITLE
Support Coinbase Wallet

### ISSUE THREAD

**Issue by SCBuergel** [omni/omnibridge-ui#380]
It seems that the current version of the Omni Bridge does not support Coinbase Wallet (I tested latest Android version). Since that's a fantastic wallet that otherwise seems to work well with products from the Gnosis family, it would be great to get that supported for the Omni Bridge.

**Comment by dan13ram** [comment]
Apologies for the delay in response, But I'm closing this as we already have support for Coinbase Wallet. Please reopen if you find any issues :)
![Screenshot from 2022-08-26 09:56:11](https://user-images.githubusercontent.com/10012209/186821951-43bdfa11-8678-4cc9-931f-39b7b6634e37.png)
